services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - cosmosdb
      - azurite
  cosmosdb:
    restart: always
    container_name: "azure-cosmosdb-emulator"
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview'
    environment:
        - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
        - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
        - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$LOCAL_HOST_IPV4
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    tty: true
    ports:
      - '1234:1234'
      - '8081:8081' 
    volumes:
      - ./data/cosmosdb:/data
  azurite:
        container_name: azurite
        image: mcr.microsoft.com/azure-storage/azurite:latest
        ports:
            - "10000:10000"
        volumes:
            - ./data/azurite:/data
networks:
  default:
    name: devcontainer_default

