services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - cosmosdb
  cosmosdb:
    restart: always
    container_name: "azure-cosmosdb-emulator"
    hostname: "azurecosmosemulator"
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    tty: true
    ports:
    - '8081:8081' # Data Explorer
    - '8900:8900'
    - '8901:8901'
    - '8902:8902'
    - '10250:10250'
    - '10251:10251'
    - '10252:10252'
    - '10253:10253'
    - '10254:10254'
    - '10255:10255'
    - '10256:10256'
    - '10350:10350'
  azurite:
        container_name: azurite
        image: mcr.microsoft.com/azure-storage/azurite:latest
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        volumes:
            - ./data/azurite:/data
networks:
  default:
    name: devcontainer_default

