version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../workspaces/tutorial-github-codespaces-poetry
    command: sleep infinity


    


  # cosmosdb:
  #   environment:
  #     AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
  #     AZURE_COSMOS_EMULATOR_PARTITION_COUNT: "1"
  #   image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
  #   networks:
  #     default: null
  #   ports:
  #     - mode: ingress
  #       target: 8081
  #       published: "8081"
  #       protocol: tcp
  #     - mode: ingress
  #       target: 10251
  #       published: "10251"
  #       protocol: tcp
  #     - mode: ingress
  #       target: 10252
  #       published: "10252"
  #       protocol: tcp
  #     - mode: ingress
  #       target: 10253
  #       published: "10253"
  #       protocol: tcp
  #   volumes:
  #     - type: volume
  #       source: cosmosdbdata
  #       target: /data
  #       volume: {}

networks:
  default:
    external: true
    name: devcontainer_default

